blank_issues_enabled: false
contact_links:
    - name: âœ¨ Feature Request
      url: https://github.com/oneunlimited/oneunlimited/discussions/categories/feature-requests?discussions_q=is%3Aopen+category%3A%22Feature+Requests%22+sort%3Atop
      about: Share and vote on feature requests for OneUnlimited
    - name: ğŸ‘‹ OneUnlimited Discord
      url: https://discord.gg/oneunlimited
      about: Join our Discord community for discussions and support
    - name: â“ Other Questions?
      url: https://x.com/sdrzn
      about: Contact the developer on X @sdrzn for other inquiries
